"""
Django settings for gestor_clientes project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'iqay!f$hj)v*-2=6lv#n=f!5ujdjz&b3!0c&*@bjw6rm(t1chp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestor_clientes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates_gestor'], # Video 12, secao 2 - Templates Django 2 Heroku
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_clientes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

    #'default': {
    #    'ENGINE': 'django.db.backends.oracle',
    #    'NAME': '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.99.100)(PORT=8415)))(CONNECT_DATA=(SERVICE_NAME=XE)))',
    #    'USER': 'HR',
    #    'PASSWORD': 'HR',
    #}
    # Erros com oracle 11
    # https://stackoverflow.com/questions/48002977/how-to-make-django-2-0-to-use-oracle-11g-syntax-instead-of-12c
    # https://stackoverflow.com/questions/28806412/sql-error-ora-02000-missing-always-keyword-when-create-identity-column-based-t
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

# Internacionalizacao
USE_I18N = True

# Regionalizacao
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# Pasta base dos arquivos Static
STATIC_URL = '/static/'

# DIRETORIO DE ARQUIVOS STATICOS. Aqui vai ser definido o nome do diretorio
STATICFILES_DIRS = [
    'estaticos',
]


# Arquivos estaticos sao colocados no servidor pelo proprio desenvolvedor
# Arquivos de midia sao colocados no servidor pelo usuario

# 1o - precisa comecar e terminar com barras
MEDIA_URL = '/media/'
#POSSIVEL ERRO:
#ERRORS:
#?: (urls.E006) The MEDIA_URL setting must end with a slash.

# 2o -Pasta onde voce vai salvar os arquivos de media.
MEDIA_ROOT = 'medias'



# de secao 2, video 14 ate secao 3, aula 19

# de secao3, aula 19 ate Secao 3, aula 20 e QUIS